### ISSUE TITLE
NullPointerException when extract tag from emf

### ISSUE THREAD

**Issue by troopson** [freehep/freehep-vectorgraphics#43]
Exception in thread "main" java.lang.NullPointerException
	at org.freehep.graphicsio.emf.EMFImageLoader.readImage(EMFImageLoader.java:271)
	at org.freehep.graphicsio.emf.gdi.StretchDIBits.read(StretchDIBits.java:95)
	at org.freehep.graphicsio.emf.EMFTag.read(EMFTag.java:38)
	at org.freehep.util.io.TaggedInputStream.readTag(TaggedInputStream.java:112)
	at com.pm.spl.Emf2text.extractText(Emf2text.java:38)
	at com.pm.Main.main(Main.java:25)

[00008.zip](https://github.com/freehep/freehep-vectorgraphics/files/1304932/00008.zip)

**Comment by daRoof** [comment]
I included a fix for this in pull request #45.

It was pretty hard to get any meaningful data from the provided file. A little more information on how to read the EMF would have been helpful.
